version: '3.1'

services:
  app:
    build: 
      context: .
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      API_HOST: ${API_HOST}
      JEPP_ENV: ${JEPP_ENV}
    ports:
      - 8880:8880
    container_name: jepp-app
    
#   db:
#     image: mariadb:10.11.3
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: jeppdb
#       MYSQL_USER: jepp-user
#       MYSQL_PASSWORD: ${MYSQL_USER_PASS}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
#     ports:
#       - 3306:3306
#     networks:
#       - jepp-net
#     volumes:
#       - db-data:/var/lib/mysql

#   adminer:
#     image: adminer
#     restart: unless-stopped
#     depends_on:
#       - db
#     ports:
#       - 8080:8080
#     networks:
#       - jepp-net

# networks:
#   jepp-net:

# volumes:
#   db-data:
