version: '3.1'

services:
  app:
    build: 
      context: .
    restart: unless-stopped
    environment:
      DB_HOST: mysql-cloud-do-user-13679810-0.b.db.ondigitalocean.com
      DB_PORT: 25060
      API_HOST: jepp.app
      JEPP_LOCAL_DEV: false
      DB_PASS: password
    ports:
      - 80:8880
      - 443:443
    container_name: jepp-app
    
  # db:
  #   image: mariadb:10.11.3
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: jeppdb
  #     MYSQL_USER: jepp-user
  #     MYSQL_PASSWORD: ${MYSQL_USER_PASS}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - jepp-net
  #   volumes:
  #     - db-data:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - jepp-net

networks:
  jepp-net:

volumes:
  db-data:
