version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  docker: ./taskfiles/docker-tasks.yml
  
tasks:
  default:
    desc: List all tasks and descriptions.
    cmds:
      - task --list-all

  generate:
    desc: Generates code.
    cmds:
      - go generate ./...
    generates:
      - internal/gqlserver/gen/generated.go
      - internal/ent/proto/*.pb.go
    sources:
      - internal/ent/entc.go
      - internal/ent/schema/*.go
      - gqlgen.yml
      - gqlschema/*.graphql

  build:
    desc: Builds jepp binary.
    deps:
      - task: generate
    cmds:
      - go build -o bin/jepp github.com/ecshreve/jepp/cmd/jepp
    generates:
      - bin/jepp
    sources:
      - cmd/jepp/*
      - internal/apiserver/apiserver.go
      - internal/gqlserver/gqlserver.go
    
  test:
    desc: Runs go tests.
    cmds:
      - go test ./...

  serve:
    desc: Runs ui and servers.
    deps:
      - task: build
    cmds:
      - ./bin/jepp
