version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    desc: List all tasks and descriptions.
    cmds:
      - task --list-all

  build:
    desc: Builds both the scraper and server binaries.
    deps:
      - go:build:scraper
      - go:build:server

  test:
    desc: Runs go tests
    cmds:
      - go test github.com/ecshreve/jepp/...


  go:build:scraper:
    desc: Builds the scraper binary.
    generates:
      - bin/scrape
    sources:
      - cmd/scrape/*.go
      - pkg/scraper/*.go
      - pkg/models/*.go
      - pkg/utils/*.go
    cmds:
      - go build -o bin/scrape github.com/ecshreve/jepp/cmd/scrape

  go:build:server:
    desc: Builds the server binary.
    generates:
      - bin/server
    sources:
      - pkg/*
      - cmd/server/main.go
    cmds:
      - go build -o bin/server github.com/ecshreve/jepp/cmd/server

  scrape:
    desc: Runs the scraper.
    deps:
      - go:build:scraper
    cmds:
      - bin/scrape

  serve:
    desc: Runs the server.
    deps:
      - go:build:server
    sources:
      - cmd/server/*
      - pkg/server/*.go
      - pkg/server/templates/**/*
      - pkg/models/*
      - pkg/utils/*
    cmds:
      - bin/server

  genswag:
    desc: Generates swagger docs for the API.
    generates:
      - docs/*
    sources:
      - cmd/server/*
      - pkg/server/*
      - pkg/models/*
      - pkg/utils/*
    cmds:
      - swag fmt -d cmd/server,pkg/server,pkg/models,pkg/utils
      - swag init -d cmd/server,pkg/server,pkg/models,pkg/utils

  docker:build:
    desc: Builds the docker image.
    deps:
      - go:build:server
    sources:
      - Dockerfile
      - docker-compose.yml
    cmds:
      - docker compose build

  docker:do:push:
    desc: Pushes the docker image to the digital ocean container registry.
    deps:
      - docker:build
    sources:
      - Dockerfile
      - docker-compose.yml
    cmds:
      - docker push registry.digitalocean.com/shreggie/jepp:custom

  docker:run:
    desc: Runs the docker image.
    deps:
      - docker:build
    sources:
      - Dockerfile
      - docker-compose.yml
    cmds:
      - docker compose up -d

  sql:dump:
    desc: Dumps the database to a file.
    cmds:
      - rm dump.sql
      - rm dump.sql.gz
      - mysqldump -u ${DB_USER} -p${DB_PASS} -h ${DB_HOST} -P ${DB_PORT} --skip-comments --column-statistics=0 --databases jeppdb > dump.sql
      - gzip dump.sql