version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task --list-all

  go:test:
    cmds:
      - go test github.com/ecshreve/jepp/...

  go:build:
    generates:
      - bin/jepp
    sources:
      - ./**/*.go
    cmds:
      - go build -o bin/jepp github.com/ecshreve/jepp/cmd/jepp

  jepp:
    deps:
      - go:build
    cmds:
      - bin/jepp {{.CLI_ARGS}}