version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task --list-all

  go:test:
    cmds:
      - go test github.com/ecshreve/jepp/...

  go:build:
    generates:
      - bin/jepp
      - bin/api
    sources:
      - ./**/*.go
    cmds:
      - go build -o bin/jepp github.com/ecshreve/jepp/cmd/jepp
      - go build -o bin/api github.com/ecshreve/jepp/cmd/api

  api:docs:
    cmds:
      - swag init -d cmd/api,pkg/api

  api:
    deps:
      - go:build
      - api:docs
    cmds:
      - bin/api {{.CLI_ARGS}}

  jepp:
    deps:
      - go:build
    cmds:
      - bin/jepp {{.CLI_ARGS}}