version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task --list-all

  test:
    cmds:
      - go test github.com/ecshreve/jepp/...

  go:build:scraper:
    desc: Builds the scraper binary.
    generates:
      - bin/scrape
    sources:
      - cmd/scrape/*.go
    cmds:
      - go build -o bin/scrape github.com/ecshreve/jepp/cmd/scrape

  go:build:server:
    desc: Builds the server binary.
    generates:
      - bin/server
    sources:
      - pkg/**/*.go
      - cmd/server/*.go
    cmds:
      - go build -o bin/server github.com/ecshreve/jepp/cmd/server

  api:docs:
    desc: Generates swagger docs for the API.
    generates:
      - docs/swagger.json
      - docs/swagger.yaml
      - docs/docs.go
    sources:
      - cmd/server/main.go
      - pkg/server/*.go
    cmds:
      - swag init -d cmd/server,pkg/server,pkg/models,pkg/utils
      - swag fmt -d cmd/server,pkg/server,pkg/models,pkg/utils

  build:
    desc: Builds both the scraper and server binaries.
    deps:
      - go:build:scraper
      - go:build:server
  
  scrape:
    desc: Runs the scraper.
    deps:
      - go:build:scraper
    cmds:
      - bin/scrape

  serve:
    desc: Runs the server.
    deps:
      - go:build:server
      - api:docs
    sources:
      - pkg/server/templates/*
      - pkg/server/*.go
    cmds:
      - bin/server