version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  docker: ./taskfiles/docker-tasks.yml
  jepp:
    taskfile: ./taskfiles/go-tasks.yml
    vars: {CMD_NAME: jepp}
  
tasks:
  default:
    desc: List all tasks and descriptions.
    cmds:
      - task --list-all

  build:
    desc: Builds all binaries.
    deps:
      - task: jepp:build
    
  test:
    desc: Runs all tests.
    deps:
      - task: jepp:test
    cmds:
      - go test ./...

  serve:
    desc: Runs the server.
    deps:
      - task: jepp:build
    sources:
      - cmd/jepp/*
      - pkg/server/*.go
      - pkg/server/templates/**/*
      - pkg/models/*
      - pkg/utils/*
    cmds:
      - ./bin/jepp
