version: '3.1'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app.dockerfile
    restart: no
    environment:
      MYSQL_DATABASE: jeppdb
      MYSQL_USER: jepp-user
      MYSQL_PASSWORD: password
      DB_HOST: db
    depends_on:
      - db
    networks:
      - jepp-net
    container_name: jepp-app
    
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jeppdb
      MYSQL_USER: jepp-user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - jepp-net
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - jepp-net

networks:
  jepp-net:

volumes:
  db-data:
