// Code generated by ent, DO NOT EDIT.

package category

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeClues holds the string denoting the clues edge name in mutations.
	EdgeClues = "clues"
	// Table holds the table name of the category in the database.
	Table = "categories"
	// CluesTable is the table that holds the clues relation/edge.
	CluesTable = "clues"
	// CluesInverseTable is the table name for the Clue entity.
	// It exists in this package in order to avoid circular dependency with the "clue" package.
	CluesInverseTable = "clues"
	// CluesColumn is the table column denoting the clues relation/edge.
	CluesColumn = "category_id"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Category queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCluesCount orders the results by clues count.
func ByCluesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCluesStep(), opts...)
	}
}

// ByClues orders the results by clues terms.
func ByClues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCluesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCluesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CluesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CluesTable, CluesColumn),
	)
}
