// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Clue is the predicate function for clue builders.
type Clue func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Season is the predicate function for season builders.
type Season func(*sql.Selector)
