// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CategoriesConnection struct {
	Edges    []*CategoriesEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type CategoriesEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Category `json:"node,omitempty"`
}

type CluesConnection struct {
	Edges    []*CluesEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type CluesEdge struct {
	Cursor string `json:"cursor"`
	Node   *Clue  `json:"node,omitempty"`
}

type GamesConnection struct {
	Edges    []*GamesEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type GamesEdge struct {
	Cursor string `json:"cursor"`
	Node   *Game  `json:"node,omitempty"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
}
