package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/ecshreve/jepp/graph/common"
	"github.com/ecshreve/jepp/graph/model"
)

// Clues is the resolver for the clues field.
func (r *queryResolver) Clues(ctx context.Context) ([]*model.Clue, error) {
	context := common.GetContext(ctx)
	var clues []*model.Clue
	err := context.Database.Find(&clues).Error
	if err != nil {
		return nil, err
	}
	return clues, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
