package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"encoding/base64"
	"fmt"
	"math"

	"github.com/ecshreve/jepp/app/models"
	"github.com/ecshreve/jepp/graph"
	"github.com/ecshreve/jepp/graph/common"
	"github.com/ecshreve/jepp/graph/model"
)

// Season is the resolver for the season field.
func (r *queryResolver) Season(ctx context.Context, seasonID string) (*model.Season, error) {
	context := common.GetContext(ctx)

	var season model.Season
	if err := context.Database.First(&season, seasonID).Error; err != nil {
		return nil, err
	}

	return &season, nil
}

// Seasons is the resolver for the seasons field.
func (r *queryResolver) Seasons(ctx context.Context) ([]*model.Season, error) {
	context := common.GetContext(ctx)

	var seasons []*model.Season
	if err := context.Database.Find(&seasons).Error; err != nil {
		return nil, err
	}

	return seasons, nil
}

// Clue is the resolver for the clue field.
func (r *queryResolver) Clue(ctx context.Context, clueID string) (*models.Clue, error) {
	context := common.GetContext(ctx)

	var clue models.Clue
	if err := context.Database.First(&clue, clueID).Error; err != nil {
		return nil, err
	}

	return &clue, nil
}

// Clues is the resolver for the clues field.
func (r *queryResolver) Clues(ctx context.Context, first *int64, after *string) (*model.CluesConnection, error) {
	context := common.GetContext(ctx)

	// The cursor is base64 encoded by convention, so we need to decode it first
	var decodedCursor string
	if after != nil {
		b, err := base64.StdEncoding.DecodeString(*after)
		if err != nil {
			return nil, err
		}
		decodedCursor = string(b)
	}

	if decodedCursor == "" {
		decodedCursor = "0"
	}

	// Here we could query the DB to get data, e.g.
	var edges []*model.CluesEdge
	hasNextPage := false

	var clues []*models.Clue
	if err := context.Database.Limit(1000).Order("id asc").Where("id > ?", decodedCursor).Find(&clues).Error; err != nil {
		return nil, err
	}

	bound := int(math.Min(float64(int(*first)), float64(len(clues))))
	for i := 0; i < bound; i++ {

		edges = append(edges, &model.CluesEdge{
			Cursor: base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", clues[i].ID))),
			Node:   clues[i],
		})
	}

	if len(edges) == int(1) && len(edges) < len(clues) {
		hasNextPage = true
	}

	pageInfo := model.PageInfo{
		StartCursor: base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", edges[0].Node.ID))),
		EndCursor:   base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", edges[len(edges)-1].Node.ID))),
		HasNextPage: &hasNextPage,
	}

	return &model.CluesConnection{
		Edges:    edges,
		PageInfo: &pageInfo,
	}, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, categoryID string) (*models.Category, error) {
	context := common.GetContext(ctx)

	var category models.Category
	if err := context.Database.First(&category, categoryID).Error; err != nil {
		return nil, err
	}

	return &category, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*models.Category, error) {
	context := common.GetContext(ctx)

	var categories []*models.Category
	if err := context.Database.Find(&categories).Error; err != nil {
		return nil, err
	}

	return categories, nil
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, gameID string) (*models.Game, error) {
	context := common.GetContext(ctx)

	var game models.Game
	if err := context.Database.First(&game, gameID).Error; err != nil {
		return nil, err
	}

	return &game, nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context) ([]*models.Game, error) {
	context := common.GetContext(ctx)

	var games []*models.Game
	if err := context.Database.Find(&games).Error; err != nil {
		return nil, err
	}

	return games, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
