package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/ecshreve/jepp/app/models"
	"github.com/ecshreve/jepp/graph"
	"github.com/ecshreve/jepp/graph/common"
)

// StartDate is the resolver for the startDate field.
func (r *seasonResolver) StartDate(ctx context.Context, obj *models.Season) (string, error) {
	context := common.GetContext(ctx)

	var season models.Season
	if err := context.Database.First(&season, obj.ID).Error; err != nil {
		return "", err
	}

	return season.StartDate.Format("2006-01-02"), nil
}

// EndDate is the resolver for the endDate field.
func (r *seasonResolver) EndDate(ctx context.Context, obj *models.Season) (string, error) {
	context := common.GetContext(ctx)

	var season models.Season
	if err := context.Database.First(&season, obj.ID).Error; err != nil {
		return "", err
	}

	return season.EndDate.Format("2006-01-02"), nil
}

// Games is the resolver for the games field.
func (r *seasonResolver) Games(ctx context.Context, obj *models.Season) ([]*models.Game, error) {
	context := common.GetContext(ctx)

	var games []*models.Game
	if err := context.Database.Where("season_id = ?", obj.ID).Find(&games).Error; err != nil {
		return nil, err
	}

	return games, nil
}

// Season returns graph.SeasonResolver implementation.
func (r *Resolver) Season() graph.SeasonResolver { return &seasonResolver{r} }

type seasonResolver struct{ *Resolver }
