package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	graph "github.com/ecshreve/jepp/graph/generated"
	"github.com/ecshreve/jepp/graph/model"
)

// Games is the resolver for the games field.
func (r *seasonResolver) Games(ctx context.Context, obj *model.Season) ([]*model.Game, error) {
	var games []*model.Game
	if err := r.DB.Where("season_id = ?", obj.ID).Find(&games).Error; err != nil {
		return nil, err
	}

	return games, nil
}

// Season returns graph.SeasonResolver implementation.
func (r *Resolver) Season() graph.SeasonResolver { return &seasonResolver{r} }

type seasonResolver struct{ *Resolver }
