type Game {
  id: ID!
  season: Season!
  show: Int!
  airDate: String!
  tapeDate: String!
  clues: [Clue!]!
}

type GamesConnection {
  edges: [GamesEdge!]!
  pageInfo: PageInfo!
}

type GamesEdge {
  cursor: ID!
  node: Game
}