// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/ecshreve/jepp/app/models"
)

type CluesConnection struct {
	Edges    []*CluesEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type CluesEdge struct {
	Cursor string       `json:"cursor"`
	Node   *models.Clue `json:"node,omitempty"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
}
