// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"github.com/go-faster/errors"
)

func (s ListCategoryCluesOKApplicationJSON) Validate() error {
	alias := ([]CategoryCluesList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
func (s ListCategoryOKApplicationJSON) Validate() error {
	alias := ([]CategoryList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
func (s ListClueOKApplicationJSON) Validate() error {
	alias := ([]ClueList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
func (s ListGameCluesOKApplicationJSON) Validate() error {
	alias := ([]GameCluesList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
func (s ListGameOKApplicationJSON) Validate() error {
	alias := ([]GameList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
func (s ListSeasonGamesOKApplicationJSON) Validate() error {
	alias := ([]SeasonGamesList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
func (s ListSeasonOKApplicationJSON) Validate() error {
	alias := ([]SeasonList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
