// Code generated by ogen, DO NOT EDIT.
package ogent

type ListCategoryCluesRes interface {
	listCategoryCluesRes()
}

type ListCategoryRes interface {
	listCategoryRes()
}

type ListClueRes interface {
	listClueRes()
}

type ListGameCluesRes interface {
	listGameCluesRes()
}

type ListGameRes interface {
	listGameRes()
}

type ListSeasonGamesRes interface {
	listSeasonGamesRes()
}

type ListSeasonRes interface {
	listSeasonRes()
}

type ReadCategoryRes interface {
	readCategoryRes()
}

type ReadClueRes interface {
	readClueRes()
}

type ReadGameRes interface {
	readGameRes()
}

type ReadSeasonRes interface {
	readSeasonRes()
}
