// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListCategory implements listCategory operation.
	//
	// List Categories.
	//
	// GET /categories
	ListCategory(ctx context.Context, params ListCategoryParams) (ListCategoryRes, error)
	// ListCategoryClues implements listCategoryClues operation.
	//
	// List attached Clues.
	//
	// GET /categories/{id}/clues
	ListCategoryClues(ctx context.Context, params ListCategoryCluesParams) (ListCategoryCluesRes, error)
	// ListClue implements listClue operation.
	//
	// List Clues.
	//
	// GET /clues
	ListClue(ctx context.Context, params ListClueParams) (ListClueRes, error)
	// ListGame implements listGame operation.
	//
	// List Games.
	//
	// GET /games
	ListGame(ctx context.Context, params ListGameParams) (ListGameRes, error)
	// ListGameClues implements listGameClues operation.
	//
	// List attached Clues.
	//
	// GET /games/{id}/clues
	ListGameClues(ctx context.Context, params ListGameCluesParams) (ListGameCluesRes, error)
	// ListSeason implements listSeason operation.
	//
	// List Seasons.
	//
	// GET /seasons
	ListSeason(ctx context.Context, params ListSeasonParams) (ListSeasonRes, error)
	// ListSeasonGames implements listSeasonGames operation.
	//
	// List attached Games.
	//
	// GET /seasons/{id}/games
	ListSeasonGames(ctx context.Context, params ListSeasonGamesParams) (ListSeasonGamesRes, error)
	// ReadCategory implements readCategory operation.
	//
	// Finds the Category with the requested ID and returns it.
	//
	// GET /categories/{id}
	ReadCategory(ctx context.Context, params ReadCategoryParams) (ReadCategoryRes, error)
	// ReadClue implements readClue operation.
	//
	// Finds the Clue with the requested ID and returns it.
	//
	// GET /clues/{id}
	ReadClue(ctx context.Context, params ReadClueParams) (ReadClueRes, error)
	// ReadGame implements readGame operation.
	//
	// Finds the Game with the requested ID and returns it.
	//
	// GET /games/{id}
	ReadGame(ctx context.Context, params ReadGameParams) (ReadGameRes, error)
	// ReadSeason implements readSeason operation.
	//
	// Finds the Season with the requested ID and returns it.
	//
	// GET /seasons/{id}
	ReadSeason(ctx context.Context, params ReadSeasonParams) (ReadSeasonRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
