# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Clue {
  id: ID!
  question: String!
  answer: String!
}

input ClueInput {
  question: String!
  answer: String!
}

type Mutation {
  createClue(input: ClueInput): Clue!
  updateClue(clueId: ID!, input: ClueInput!): Clue!
  deleteTodo(clueId: ID!): Clue!
}

type Query {
  clues: [Clue!]!
  clue(clueId: ID!): Clue!
}