type Clue {
  id: ID!
  question: String!
  answer: String!
  category: Category!
  game: Game!
}

type CluesConnection {
  edges: [CluesEdge!]!
  pageInfo: PageInfo!
}

type CluesEdge {
  cursor: ID!
  node: Clue
}

type PageInfo {
  startCursor: ID!
  endCursor: ID!
  hasNextPage: Boolean
}