type Query {
  season(seasonID: ID!): Season!
  seasons: [Season!]!
  
  clue(clueID: ID!): Clue!
  clues(first: Int = 10, after: ID): CluesConnection

  category(categoryID: ID!): Category!
  categories(first: Int = 10, after: ID): CategoriesConnection

  game(gameID: ID!): Game!
  games: [Game!]!
}

type PageInfo {
  startCursor: ID!
  endCursor: ID!
  hasNextPage: Boolean
}