type Season {
  id: ID!
  number: Int!
  startDate: String!
  endDate: String!
}

type Query {
  clue(clueID: ID!): Clue!
  clues: [Clue!]!
  category(categoryID: ID!): Category!
  categories: [Category!]!
  season(seasonID: ID!): Season!
  seasons: [Season!]!
  game(gameID: ID!): Game!
  games: [Game!]!
}