basePath: /api
definitions:
  models.Category:
    properties:
      categoryId:
        example: 765
        type: integer
      name:
        example: State Capitals
        type: string
    type: object
  models.Clue:
    properties:
      answer:
        example: This is the answer.
        type: string
      categoryId:
        example: 804092001
        type: integer
      clueId:
        example: 804002032
        type: integer
      gameId:
        example: 8040
        type: integer
      question:
        example: This is the question.
        type: string
    type: object
  models.Game:
    properties:
      gameDate:
        example: "2019-01-01"
        type: string
      gameId:
        example: 8040
        type: integer
      seasonId:
        example: 38
        type: integer
      showNum:
        example: 4532
        type: integer
      tapedDate:
        example: "2019-01-01"
        type: string
    type: object
  utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact:
    name: shreve
  description: This is a simple api to access jeopardy data.
  license:
    name: MIT License
    url: https://github.com/ecshreve/jepp/blob/main/LICENSE
  title: Jepp API Documentation
  version: "1.0"
paths:
  /category:
    get:
      consumes:
      - application/json
      description: get categories with optional filters
      parameters:
      - description: If exists or true, returns `limit` random records.
        in: query
        name: random
        type: boolean
      - description: If exists, returns the record with the given id.
        in: query
        name: id
        type: integer
      - default: 10
        description: Limit the number of records returned.
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Fetch categories
      tags:
      - api
  /clue:
    get:
      consumes:
      - application/json
      description: get clues with optional filters
      parameters:
      - description: If exists or true, returns `limit` random records.
        in: query
        name: random
        type: boolean
      - description: If exists, returns the record with the given id.
        in: query
        name: id
        type: integer
      - description: Filter by Game ID
        in: query
        name: game
        type: integer
      - description: Filter by Category ID
        in: query
        name: category
        type: integer
      - default: 10
        description: Limit the number of records returned
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Clue'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Fetch Clues
      tags:
      - api
  /game:
    get:
      consumes:
      - application/json
      description: get games with optional filters
      parameters:
      - description: If exists or true, returns `limit` random records.
        in: query
        name: random
        type: boolean
      - description: If exists, returns the record with the given id.
        in: query
        name: id
        type: integer
      - default: 10
        description: Limit the number of records returned.
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Game'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Fetch Games
      tags:
      - api
swagger: "2.0"
