definitions:
  models.CategoryCount:
    properties:
      categoryId:
        example: CATEGORYNAME0000
        type: string
      categoryName:
        example: Category Name
        type: string
      clueCount:
        example: 5
        type: integer
      gameCount:
        example: 1
        type: integer
    type: object
  models.Clue:
    properties:
      answer:
        example: This is the answer.
        type: string
      categoryId:
        example: CATEGORYNAME0000
        type: string
      clueId:
        example: 804002032
        type: integer
      gameId:
        example: 8040
        type: integer
      question:
        example: This is the question.
        type: string
    type: object
  models.Game:
    properties:
      gameDate:
        example: "2019-01-01"
        type: string
      gameId:
        example: 8040
        type: integer
      showNum:
        example: 4532
        type: integer
    type: object
  utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact:
    email: eric@shreve.dev
    name: shreve
    url: http://github.com/ecshreve
  license:
    name: MIT
    url: https://github.com/ecshreve/jepp/blob/main/LICENSE
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: Show available endpoints
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Base handler
      tags:
      - root
  /categories:
    get:
      consumes:
      - '*/*'
      description: Returns a list of categories.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CategoryCount'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a list of categories.
      tags:
      - category
  /categories/{categoryID}:
    get:
      consumes:
      - '*/*'
      description: Returns a category
      parameters:
      - default: 10LETTERWORDS000
        description: Category ID
        in: path
        name: categoryID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CategoryCount'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a category
      tags:
      - category
  /categories/random:
    get:
      consumes:
      - '*/*'
      description: Returns a random category
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CategoryCount'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a random category
      tags:
      - category
      - random
  /clues:
    get:
      consumes:
      - '*/*'
      description: Returns a list of clues
      parameters:
      - description: Game ID
        in: query
        name: game
        type: string
      - description: Category ID
        in: query
        name: category
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Clue'
            type: array
      summary: Returns a list of clues
      tags:
      - clue
  /clues/{clueID}:
    get:
      consumes:
      - '*/*'
      description: Returns a clue
      parameters:
      - default: "708002056"
        description: Clue ID
        in: path
        name: clueID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Clue'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a clues
      tags:
      - clue
  /clues/random:
    get:
      consumes:
      - '*/*'
      description: Returns a random clue
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Clue'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a random clue
      tags:
      - clue
      - random
  /games:
    get:
      consumes:
      - '*/*'
      description: Returns a list of games
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Game'
            type: array
      summary: Returns a list of games
      tags:
      - game
  /games/{gameID}:
    get:
      consumes:
      - '*/*'
      description: Returns a game
      parameters:
      - default: "7000"
        description: Game ID
        in: path
        name: gameID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Game'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a games
      tags:
      - game
  /games/random:
    get:
      consumes:
      - '*/*'
      description: Returns a random game
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Game'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Returns a random game
      tags:
      - game
      - random
  /ping:
    get:
      consumes:
      - '*/*'
      description: Get the status of server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server
      tags:
      - root
swagger: "2.0"
