// Code generated by ent, DO NOT EDIT.

package game

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldShow holds the string denoting the show field in the database.
	FieldShow = "show"
	// FieldAirDate holds the string denoting the airdate field in the database.
	FieldAirDate = "air_date"
	// FieldTapeDate holds the string denoting the tapedate field in the database.
	FieldTapeDate = "tape_date"
	// FieldSeasonID holds the string denoting the season_id field in the database.
	FieldSeasonID = "season_id"
	// EdgeSeason holds the string denoting the season edge name in mutations.
	EdgeSeason = "season"
	// EdgeClues holds the string denoting the clues edge name in mutations.
	EdgeClues = "clues"
	// Table holds the table name of the game in the database.
	Table = "games"
	// SeasonTable is the table that holds the season relation/edge.
	SeasonTable = "games"
	// SeasonInverseTable is the table name for the Season entity.
	// It exists in this package in order to avoid circular dependency with the "season" package.
	SeasonInverseTable = "seasons"
	// SeasonColumn is the table column denoting the season relation/edge.
	SeasonColumn = "season_id"
	// CluesTable is the table that holds the clues relation/edge.
	CluesTable = "clues"
	// CluesInverseTable is the table name for the Clue entity.
	// It exists in this package in order to avoid circular dependency with the "clue" package.
	CluesInverseTable = "clues"
	// CluesColumn is the table column denoting the clues relation/edge.
	CluesColumn = "game_id"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldShow,
	FieldAirDate,
	FieldTapeDate,
	FieldSeasonID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByShow orders the results by the show field.
func ByShow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShow, opts...).ToFunc()
}

// ByAirDate orders the results by the airDate field.
func ByAirDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAirDate, opts...).ToFunc()
}

// ByTapeDate orders the results by the tapeDate field.
func ByTapeDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTapeDate, opts...).ToFunc()
}

// BySeasonID orders the results by the season_id field.
func BySeasonID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonID, opts...).ToFunc()
}

// BySeasonField orders the results by season field.
func BySeasonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeasonStep(), sql.OrderByField(field, opts...))
	}
}

// ByCluesCount orders the results by clues count.
func ByCluesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCluesStep(), opts...)
	}
}

// ByClues orders the results by clues terms.
func ByClues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCluesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSeasonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeasonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeasonTable, SeasonColumn),
	)
}
func newCluesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CluesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CluesTable, CluesColumn),
	)
}
