name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_NAME: testdb
  DB_USER: root
  DB_PASS: root
  DB_HOST: localhost
  DB_PORT: 3306
  JEPP_ENV: test

jobs:
  test-with-db:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.25.0

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Initialize MySQL
        run: sudo systemctl start mysql.service

      - name: Initialize first database
        run: |
          mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' \
          -u${{ env.DB_USER }} -p${{ env.DB_PASS }}

      - name: Boost user perms
        run: |
          mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';" \
          -u${{ env.DB_USER }} -p${{ env.DB_PASS }}

      - name: Restore test database
        run: task sql:restore

      - name: Build
        run: task build
          
      - name: Test
        run: task test
