name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  JEPP_DB_HOST: localhost

jobs:
  test-with-db:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.25.0

      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Start db container
        run: docker compose up -d db

      - name: Build
        run: task build
          
      - name: Test
        run: task test
