name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  JEPP_ENV: ci
  JEPP_DB_HOST: localhost

jobs:
  test-with-db:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.25.0

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Initialize MySQL
        run: sudo systemctl start mysql.service

      - name: Initialize first database
        run: |
          mysql -e 'CREATE DATABASE jeppdb;' \
          -u root -proot

      - name: Boost user perms
        run: |
          mysql -e "ALTER USER 'root'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';" \
          -u root -proot

      - name: Restore database
        run: gunzip -c ./data/dump.sql.gz | mysql -u root -proot jeppdb

      - name: Build
        run: task build
          
      - name: Test
        run: task test
