
name: Publish

on:
  release:
    types: [published]

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: jepp-app

jobs:
  upload-files-to-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload data files to GitHub release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: data/*{.csv,.gz}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . -t registry.digitalocean.com/shreggie/jepp:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image
        run: |
          docker push registry.digitalocean.com/shreggie/jepp:latest
