
name: Publish

on:
  push:
    tags: [ "*" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: 3.25.0
          
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build binaries
      run: task build

    - name: Run tests
      run: task test

    - name: Dump db
      run: task sql:dump

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.6.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dump.sql.gz
        tag: ${{ github.ref }}
        overwrite: true


    
